version: '3'
services:
    mysql-container:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=password
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - service-tier
      container_name: ${CONTAINER_NAME}_sql

    booth-service:
      image: booth-backend
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://${CONTAINER_NAME}_sql:3306/booth?createDatabaseIfNotExist=true&useSSL=false
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_CLOUD_VAULT_HOST=vault
        - BLOCKCHAIN_VIEW_URL=http://host.docker.internal:5790/getAllVotes
        - BLOCKCHAIN_VOTE_URL=http://host.docker.internal:5790/vote
        - NOMINEE_VOTE_TOKEN_URL=http://host.docker.internal:5790/authenticate
        - NOMINEE_TOKEN_URL=http://host.docker.internal:5792/authenticate
        - ADMIN_VIEW_NOMINEES=http://host.docker.internal:5792/nominee/getNomineeByCity
      networks:
      - service-tier
      restart: on-failure
      depends_on:
        - mysql-container
      container_name: ${CONTAINER_NAME}
      extra_hosts:
        - "host.docker.internal:host-gateway"

    booth-frontend:
      image: booth-frontend
      ports:
        - ${CONTAINER_PORT}:80
      depends_on:
        - booth-service
      environment:
        - CONTAINER_URL=${CONTAINER_NAME}
        - VITE_PUBLIC_URL=/api
        - VITE_CITY=${CONTAINER_NAME}
      restart: on-failure
      networks:
      - service-tier
volumes:
  db_data:

networks:
  service-tier:
    name: service-tier
    external: true